#![allow(clippy::all, clippy::pedantic, clippy::nursery, clippy::restriction)]
//! Build-generated Valence models for identity tables.
//!
//! Generated by `build.rs` from `schemas/*_valence_schema.rs` via `valence_codegen`;
//! do not hand-edit.
#![allow(unused_imports)]
#![allow(missing_docs)]

use valence::privacy_policies::common::{AUTHENTICATED, PUBLIC_READ, SYSTEM_ONLY};
use valence::privacy_policies::owner::{OWNER_BY_ID, OWNER_BY_USER_FIELD};

use crate::side_effects::ClearAccountPrimaryOnMembershipDelete;

include!(concat!(env!("OUT_DIR"), "/generated_models.rs"));
